POST  http://localhost:5000/api/v1/login/
Content-Type: application/json

{ 
    "name":"admin",
    "email" : "admin@localhost.com",
    "password": "admin",
    "confPassword": "admin"
}





###

GET http://localhost:5000/api/v1/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NzljYTU0NWE5NmIzZDM2NzAxYjhjYzIiLCJuYW1lIjoiYWRtaW4iLCJlbWFpbCI6ImFkbWluQGxvY2FsaG9zdC5jb20iLCJpYXQiOjE3Mzg1OTU0MjksImV4cCI6MTczODY4MTgyOX0.K0SUDL08HcxNZNl-ptROVzm6tEyZoJ5qzBJevAbF13o