GET http://localhost:5000/api/v1/suppliers/




###
POST http://localhost:5000/api/v1/suppliers
Content-Type: application/json

{
    "name": "Wendy plastik",
    "email": "wend@gmail.com",
    "phone": "088921223123",
    "address": "Bantar Listrik Gerbang 2"
}

####
//update supplier
PUT http://localhost:5000/api/v1/suppliers/1
Content-Type: application/json

{
    "name": "Wendy Listrik",
    "email": "gerd@gmail.com",
    "phone": "08892123123",
    "address": "Bantar Listrik Gerbang"
}

###
//delete supplier
DELETE http://localhost:5000/api/v1/suppliers/63f5c86b812033745f1b6c58